---
- name: Configure Upright cluster nodes
  hosts: all_upright
  any_errors_fatal: true
  gather_facts: true
  become: true
  vars_files:
    - group_vars/linode/vars
  pre_tasks:
    - name: Wait for SSH connectivity
      ansible.builtin.wait_for_connection:
        timeout: 900
        connect_timeout: 10
        sleep: 5

    - name: Wait for cloud-init completion when present
      ansible.builtin.shell: |
        if command -v cloud-init >/dev/null 2>&1; then
          timeout 900 cloud-init status --wait
        fi
      args:
        executable: /bin/bash
      changed_when: false
  roles:
    - common

- name: Write post-deploy operator notes
  hosts: app
  gather_facts: false
  become: true
  vars_files:
    - group_vars/linode/vars
  roles:
    - post
